name: CI Pipeline for Module_01 only Daily check

on:
  schedule:
      - cron: '0,30 3,4 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build project
      run: |
        cd Module_01
        ./Mod_test.sh

    - name: Check build status
      if: ${{ failure() }}
      run: |
        echo "Build failed,."
        gh pr close ${{ github.event.pull_request.number }} --comment "Build failed."

    - name: Run tests
      if: ${{ success() }}
      run: |
        cd Module_01/build/tests
        ./testexe

    - name: Check test status
      if: ${{ failure() }}
      run: |
        echo "Test failed,."
        gh pr close ${{ github.event.pull_request.number }} --comment "Test failed."

    - name : Inform success
      if: ${{ success() }}
      run: |
        echo "Test Passed,."
